// @ts-nocheck
// このファイルは自動生成されます。手編集しないでください（GEN-03）。
// 生成: `pnpm generate:bindings`
// イベント未使用時に生じる未使用シンボルの警告を避けるため型チェック対象から外す。

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * サンプルコマンド。フロントの型付き呼び出し（tauri-specta, RS-05）を実演する。
 */
async greet(name: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * フロントから渡された秘密情報を OS キーチェーンに保存する。保存後は破棄され、
 * 二度とフロントへは返らない（SEC-04, RS-12）。
 */
async saveCredential(account: string, secret: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_credential", { account, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 値そのものではなく「保存されているか」だけをフロントに返す。
 */
async hasCredential(account: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_credential", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCredential(account: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_credential", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * RS-10: 進捗イベントを伴う長時間処理のサンプル。即座にタスク ID を返し、
 * 実処理はバックグラウンドで進める。フロントは `TaskProgress` イベントを購読して
 * 進捗バーを更新し、`cancel_long_task` でキャンセルできる。
 */
async startLongTask(steps: number) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_long_task", { steps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelLongTask(taskId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_long_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * RS-09 のサンプルコマンド。SQL 組み立てとコンパイル時検証は `app_core::domain::notes` 側
 * （`sqlx::query!`）に閉じ、ここでは呼び出しと State からの取得のみを行う。
 */
async createNote(title: string, body: string) : Promise<Result<Note, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNotes() : Promise<Result<Note[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * #6 のコマンド。SQL 組み立てとコンパイル時検証は `app_core::domain::book` 側
 * （`sqlx::query_as!`）に閉じ、ここでは呼び出しと State からの取得のみを行う
 * （`notes` コマンドと同じ薄いアダプタ層のパターン。docs/testing.md §3）。
 */
async listBooks() : Promise<Result<Book[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_books") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBook(id: number) : Promise<Result<Book, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_book", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBook(input: NewBook) : Promise<Result<Book, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_book", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateBook(id: number, input: NewBook) : Promise<Result<Book, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_book", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBook(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_book", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * #12 のコマンド。全ての本を CSV にして `path` へ書き出し、書き出した件数を返す。
 * 実際の CSV 組み立てとファイル I/O は `app_core::domain::book::export_csv` に閉じる。
 */
async exportBooks(path: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_books", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * #14: スキャンまたは手入力したISBNから書名・著者を引く。実際のHTTP通信（タイムアウト・
 * リトライ）は `http_client` に委ね、レスポンスの解釈は `app_core::openbd`（純粋関数、
 * ネットワークなしでテスト済み）に委ねる。該当するISBNが見つからない場合も
 * エラーにはせず、`title`/`author` が空の `BookInfo` を返す（呼び出し側で手入力に
 * フォールバックできるようにするため）。
 */
async lookupIsbn(isbn: string) : Promise<Result<BookInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_isbn", { isbn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * FE-06: フロントの初期化が完了したらメイン画面から呼び出す。スプラッシュを閉じて
 * メインウィンドウを表示する。デスクトップ・モバイル双方の window 構成で動作する。
 */
async closeSplashscreen() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_splashscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * APP-08: 自動アップデート。署名検証は tauri-plugin-updater が config の pubkey に基づき
 * 行う（CI-05 で鍵と配信マニフェストを生成する）。デスクトップのみで意味を持つ機能
 * （§3, レビュー観点 §3）。
 */
async checkForUpdate() : Promise<Result<UpdateInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * アップデートをダウンロードして適用する。呼び出し後はアプリの再起動が必要。
 */
async installUpdate() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
taskProgress: TaskProgress
}>({
taskProgress: "task-progress"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * コマンド層の統一エラー型。`app_core::CoreError` をそのまま包み、フロントには
 * serde を通じて型付きで伝わる（RS-04）。コマンド内で `unwrap()` / `expect()` は使わず、
 * 必ずこの型に変換して `Result` として返すこと（レビュー観点 §2）。
 * 
 * `Database` / `Migration` / `Path` は `sqlx::Error` / `sqlx::migrate::MigrateError` /
 * `tauri::Error` をそれぞれ表す（#5）。これら3つは `Serialize` を実装しないため
 * `#[from]` で直接包めず、メッセージを文字列化した上で保持する。DB 接続自体のエラーは
 * `app_core::CoreError::Internal` に正規化されるため（`crates/core/src/domain/notes.rs`
 * 参照）、ここでの `Database` / `Migration` / `Path` は起動時のセットアップや今後の
 * コマンド実装が `?` でそのまま伝搬できるようにするための受け皿である。
 */
export type AppError = { kind: "Core"; message: CoreError } | { kind: "Io"; message: string } | { kind: "Database"; message: string } | { kind: "Migration"; message: string } | { kind: "Path"; message: string } | 
/**
 * #14: `lookup_isbn` が openBD を呼ぶ際のHTTP通信の失敗（タイムアウト・DNS解決失敗等）。
 */
{ kind: "Network"; message: string }
/**
 * データベースから読み出した本のレコード。
 */
export type Book = { id: number; title: string; author: string; status: ReadingStatus; note: string; genre: Genre; isbn: string; created_at: string }
/**
 * 書誌情報APIから引いた書名と著者。該当するISBNが見つからない場合は両方とも
 * 空文字のまま返し、利用者が手で埋められるようにする（スキャンは入力の手間を
 * 減らす手段であって、登録できる条件を狭める手段にしてはいけないため）。
 */
export type BookInfo = { title: string; author: string }
/**
 * アプリ全体で共有する統一エラー型（RS-04）。
 * 
 * `crates/core` の全ての公開関数はこの型（または個別の `thiserror` 型を経由してこの型へ
 * 変換されるもの）を返す。`src-tauri` のコマンド層はこれを `serde` でフロントへシリアライズする。
 */
export type CoreError = { kind: "InvalidInput"; message: string } | { kind: "NotFound"; message: string } | 
/**
 * #14: 一意制約（例: ISBNの重複）に違反した場合のユーザー向けエラー。
 */
{ kind: "Conflict"; message: string } | { kind: "Internal" }
/**
 * 本のジャンル。
 */
export type Genre = "novel" | "non_fiction" | "business" | "technology" | "other"
/**
 * 新規登録時にフロントエンドから受け取る入力。`isbn` は分かっているときだけ入れる項目
 * なので空文字を許す（#14）。
 */
export type NewBook = { title: string; author: string; status: ReadingStatus; note: string; genre: Genre; isbn: string }
export type Note = { id: number; title: string; body: string }
/**
 * 本を読み終えているかどうかの状態。文字列ではなく列挙型にすることで、
 * 打ち間違いをコンパイルで止める。
 */
export type ReadingStatus = "unread" | "reading" | "finished"
export type TaskProgress = { task_id: string; completed: number; total: number; status: TaskStatus }
export type TaskStatus = "running" | "completed" | "cancelled"
export type UpdateInfo = { available: boolean; version: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
